# Brewfile

# Tap sources
tap homebrew/dupes
tap homebrew/science
tap homebrew/versions
tap josegonzalez/php
tap nviennot/tmate
tap phinze/cask
tap thoughtbot/formulae

# Install
install apple-gcc42
install wget
install ghostscript
install libpng
install pcre
install sbt
install autoconf
install git
install libtiff
install phantomjs
install scala
install automake
install gmp
install libtool
install php54
install sqlite
install brew-cask
install gradle
install libxml2
install php54-intl
install the_silver_searcher
install cloog
install graphviz
install libxslt
install pkg-config
install tmate
install cmake
install icu4c
install libyaml
install postgresql
install tmux
install cscope
install imagemagick
install little-cms2
install pyenv
install unixodbc
install curl-ca-bundle
install isl
install lua
install pyenv-virtualenv
install vim
install elasticsearch
install jbig2dec
install macvim
install python
install xz
install fontconfig
install jpeg
install mercurial
install python3
install yajl
install fontforge
install leiningen
install mpfr
install r
install zlib
install freetype
install libevent
install mysql
install rbenv
install zsh
install gd
install libffi
install nmap
install rcm
install gdbm
install libiconv
install node
install readline
install gettext
install libmagic
install openssl
install reattach-to-user-namespace
install gfortran
install libmpc
install ossp-uuid
install ruby-build
